theme: jekyll-theme-hacker
title: Welcome to my green-top home! :^P
description: 'Green-top' is in reference to Minecraft. Specifically, it references how a person unfamiliar with Minecraft, may build their house in-game with dirt that they acquired and in turn have grass grow on the roof of their home. This results in their home having a 'green top' and signals to others the incompetency of the builder.
